config/routes.rb
Rails.application.routes.draw do

  resources :test_urls
  root 'pages#test_page'
  post 'test' => 'pages#url_test', as: :url_test
  post 'restart' => 'test_urls#restart', as: :restart
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test_url.rb
class TestUrl < ApplicationRecord
	validates :url, :request, :presence => true
	include ActionView::Helpers::DateHelper
	require 'twilio-ruby'
	require 'rake'

	def self.create_fatj_sweeper(params)
		TestUrl.create({:url => "http://www.findatruckerjob.com/jobs?company=", :request => "GET", :frequency => params[:frequency], :role => "fatj-sweeper"})
	end

	def self.send_mms(response)
		client = Twilio::REST::Client.new ENV['ACCOUNT_SID'], ENV['AUTH_TOKEN']
		client.messages.create(
		  from: '+17868375211',
		  to: "#{ENV['TWILIO_NUMBER']}",
		  body: "Alert!!! Code #{response.code} for #{response.request.last_uri.to_s}, pinged #{Time.now.strftime("%A%l:%M %P at %B %d, %Y")}" ,
		  media_url: 'http://vignette1.wikia.nocookie.net/cybernations/images/0/03/Nuke.jpg/revision/latest?cb=20060723162018'
		)
	end

	def set_task
		scheduler = Rufus::Scheduler.new
		scheduler.every self.frequency do
		  self.request == "GET" ? response=self.get : response=self.post(self.post_params)
			self.update_attributes(last_request: Time.now)
		  if response.code == (404 || 500)
		  	# Expand on condition/refactor for more cases, and begin Post design
		  	TestUrl.send_mms(response)
		  end
		  self.logger(response)
		end
	end

	def set_fatj_sweep
		scheduler = Rufus::Scheduler.new
		scheduler.every self.frequency do
		  self.ping_fatj_company_job_index
		  self.ping_fatj_company_job_pages
			self.update_attributes(last_request: Time.now)
		end
	end

  def self.fatj_slug_array
  	slugs=HTTParty.get("http://www.findatruckerjob.com/api/companies/slugs")
		JSON.parse(slugs.body)
  end

	def ping_fatj_company_job_index
		TestUrl.fatj_slug_array.each do |slug|
			response=HTTParty.get("http://www.findatruckerjob.com/jobs?company=#{slug}")
		  if response.code == (404 || 500)
		  	TestUrl.send_mms(response)
		  end
		  self.logger(response)
		end
	end

  def self.fatj_urls_array
		urls=HTTParty.get("http://www.findatruckerjob.com/api/companies/job_sample")
		JSON.parse(urls.body)
  end

	def ping_fatj_company_job_pages
		TestUrl.fatj_urls_array.each do |url|
			response=HTTParty.get(url)
			if response.code == (404 || 500)
		  	TestUrl.send_mms(response)
		  end
		  self.logger(response)
		end
	end

	def logger(response)
		Rails.logger.info "Code #{response.code} for #{response.request.last_uri.to_s}, pinged #{Time.now.strftime("%A%l:%M %P at %B %d, %Y")}, next ping in #{self.frequency}"
	end

	def get
		HTTParty.get(self.url)
	end

	def post(params)
		HTTParty.post(self.url,eval(params))
	end

	private

	def self.run_rake(task)
    load File.join("#{Rails.root}", 'lib', 'tasks', "heroku.rake")
    Rake::Task[task].invoke
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def test_page
	end

	def url_test
		if params[:request_type] == "GET"
			@response = HTTParty.get(params[:test_url])
		else
			@response = HTTParty.post(params[:test_url], eval(params[:post_params]))
		end
		respond_to do |format|
			format.js{ render :partial => 'pages/url_response_form' }
		end
	end
end

app/controllers/test_urls_controller.rb
class TestUrlsController < ApplicationController
  before_action :set_test_url, only: [:show, :edit, :update, :destroy]
  before_action :set_form_if_url, only: [:new]
  def index
    @test_urls = TestUrl.all
  end

  def show
  end

  def new
    @test_url = TestUrl.new
  end

  def edit
  end

  def create
    params['fatj-sweeper'] ? @test_url = TestUrl.create_fatj_sweeper(params[:test_url]) : @test_url = TestUrl.create(test_url_params)
    if @test_url.save
      flash[:success]='Test url was successfully created.'
      redirect_to @test_url
    else
      flash[:alert]='Test url was not successfully created.'
      redirect_to new_test_url_path
    end
  end

  def update
    @test_url.update_attributes(test_url_params)
      if @test_url.update(test_url_params)
        flash[:success]='Test url was successfully updated.'
        redirect_to @test_url
      else
        flash[:alert]='Test url was not successfully updated.'
        redirect_to new_test_url_path
      end
  end

  def destroy
    @test_url.destroy
    flash[:success] = "Test Url successfully destroyed!"
    redirect_to test_urls_path
  end

  def restart
    flash[:success]='Refreshing! One moment please!'
    redirect_to test_urls_path
    TestUrl.run_rake('heroku:restart')
  end

  private


    def set_form_if_url
      if params[:url_text]
        @url=params[:url_text]
        @request=params[:request]
        @response=HTTParty.get(params[:url_text])
        @post_params = params[:post_params]
      end
    end

    def set_test_url
      @test_url = TestUrl.find(params[:id])
    end

    def test_url_params
      params.require(:test_url).permit(:url, :request, :post_params, :response_code, :response_body, :frequency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def humanize_last_request_for(test_url, time)
		distance_of_time_in_words(test_url.last_request, time) if test_url.last_request.present?
	end

	def sweeper_or_url(test_url)
		test_url.url == "http://www.findatruckerjob.com/jobs?company=" ? "FATJ company index page tester" : test_url.url
	end
end

app/helpers/test_urls_helper.rb
module TestUrlsHelper
end

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="center alert alert-<%= key %>">
  	<button type="button" class="close" data-dismiss="alert">×</button>
    <ul>
        <%= value %>
    </ul>
  </div>
<% end %>

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinger</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/bootstrap' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
  	<div class="container">
      <div class="row center">
        <%= link_to "Test Url Index", test_urls_path, class:"btn btn-primary home-button" %>
      </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_url_response_form.html.erb
<%= form_tag(new_test_url_path, :method => "get", class:"new_url_form") do %>

  <%= hidden_field_tag :url_text %>
  <%= hidden_field_tag :request %>
  <%= hidden_field_tag :post_params %>

    <%= label_tag :code %>
  <div class="row center">
    <%= @response.code %>
  </div>

    <%= label_tag :message %>
  <div class="row center">
    <%= @response.message %>
  </div>

    <%= label_tag :headers %>
  <div class="row center overflow">
    <%= @response.headers.inspect %>
  </div>

    <%= label_tag :body %>
  <div class="row center overflow">
    <%= @response.body %>
  </div>

  <div class="actions">
    <%= button_tag(class:"btn btn-primary", type: 'submit') do %>
      <%= content_tag(:strong, 'Transfer Response To Form') %>
    <% end %>
  </div>

<% end %>

<script type="text/javascript">
  $( document ).ready(function() {
    url=$('.url-text-field').val();
    request=$('select#test_url_request').val();
    post_params=$('textarea#test_url_post_params').val();
    // post_params=
    $('#url_text').attr('value', url)
    $('input#request').attr('value', request)
    $('input#post_params').attr('value', post_params)
  });
   
</script>

app/views/pages/_url_response_form.js.erb
$('.url_form_div').html("<%= escape_javascript(render :partial => 'url_response_form.html.erb') %>");

app/views/pages/test_page.html.erb
<div class="center">
  <div class="field">
    <%= label_tag :url %>
    <%= text_field_tag :url, params[:location], placeholder:"Url", class: "form-control url-text-field" %>
  </div>
  <div class="field">
    <%= label_tag :request %>
    <%= select_tag "test_url_request", options_for_select(["GET", "POST"]), class:"form-control"   %>
  </div>
  <div class="field hidden" id="post-input">
    <%= label_tag :post_params %>
    <%= text_area_tag "test_url_post_params", nil, class: "form-control post-params-text-field" %>
  </div>
  <%= button_tag(class:"btn btn-primary test-button", type: 'button') do %>
    <%= content_tag(:strong, 'Click Me!') %>
  <% end %>
  <div class="url_form_div center">
  </div>
</div>
<script type="text/javascript">
  $("#test_url_request").change(function() {
    if($('#post-input:hidden').length==0) {
      $('#post-input:visible').addClass('hidden');
    }
    else {
      $('#post-input:hidden').removeClass('hidden');
    }
  });

$('.test-button').bind('click', function() {
  test_url=$('.url-text-field').val();
  request=$('#test_url_request').val();
  post_params=$('#test_url_post_params').val();
  
  $.ajax({
    url: '/test',
    type: 'POST',
    data: {
      test_url: test_url,
      request_type: request,
      post_params: post_params
    }
  });
});
</script>

app/views/test_urls/_form.html.erb
<div class="center">
  <%= form_for(test_url) do |f| %>
    <% if test_url.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(test_url.errors.count, "error") %> prohibited this test_url from being saved:</h2>
        <ul>
        <% test_url.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= label_tag :Create_New_Fatj_sweeper %>
      <br>
      <%= check_box_tag 'fatj-sweeper', true, false, class: 'fatj-sweeper-check-box' %>
    </div>
    <div class="primary-fields">
      <div class="field">
        <%= label_tag :url %>
        <%= f.text_field :url, placeholder:"Url", :value => @url, class: "form-control url-text-field" %>
      </div>
      <div class="field">
        <%= label_tag :request %>
        <%= select_tag "test_url[request]", options_for_select(["GET", "POST"], (@request ? @request : "GET")), class:"form-control request-text-field" %>
      </div>
      <div class="field hidden" id="post-input">
        <%= label_tag :post_params %>
        <%= f.text_area :post_params, placeholder:"Post Params", :value => (@post_params ? @post_params : ''), class: "form-control post-params-text-field" %>
      </div>
      <%= button_tag(class:"btn btn-primary test-button", type: 'button') do %>
        <%= content_tag(:strong, 'Click to Test Url!') %>
      <% end %>
      <div class="field">
        <%= label_tag :response_code %>
        <%= f.text_field :response_code, placeholder:"Response Code", :value => (@response ? @response.code : ''), class: "form-control response_code-text-field" %>
      </div>
      <div class="field">
        <%= label_tag :response_body %>
        <%= f.text_area :response_body, placeholder:"Response Body", :value => (@response ? @response.body : ''), class: "form-control response_body-text-field" %>
      </div>
    </div>
    <div class="field">
      <%= label_tag :ping_interval %>
      <br>
      <%= select_tag "frequency_amount", options_for_select((1..100).each.collect {|i|[i]})%>
      <%= select_tag "frequency_metric", options_for_select([["Second", "s"], ["Minute", "m"], ["Hour", "h"], ["Day", "d"]])%>
      <%= hidden_field_tag "test_url[frequency]"%>
    </div>
    <div class="actions">
      <%= f.submit "Create Test Url", :class=>"btn btn-primary test_url_create"  %>
    </div>
  <% end %>
</div>
<div class="center">
  <div class="url_form_div">
  </div>
</div>

<script type="text/javascript">
// FATJ SWEEPER BUTTON
$('.fatj-sweeper-check-box').click(function(){
  $('div.primary-fields').toggle("hidden");
});
// POST PARAMS HIDER
  $("#test_url_request").change(function() {
    if($('#post-input:hidden').length==0) {
      $('#post-input:visible').addClass('hidden');
    }
    else {
      $('#post-input:hidden').removeClass('hidden');
    }
  });
// FREQUENCY FIELD VALUE GENERATOR
  $('input.test_url_create').bind('click', function() {
    amount=$('#frequency_amount').val();
    metric=$('#frequency_metric').val();
    $('#test_url_frequency').attr('value', amount+metric)
  });
// REQUEST TEST BUTTON AJAX
  $('.test-button').bind('click', function() {
    test_url=$('.url-text-field').val();
    request=$('#test_url_request').val();
    post_params=$('#test_url_post_params').val();

    $.ajax({
      url: '/test',
      type: 'POST',
      data: {
        test_url: test_url,
        request_type: request,
        post_params: post_params
      }
    });
  });
</script>

app/views/test_urls/edit.html.erb
<h1>Editing Test Url</h1>

<%= render 'form', test_url: @test_url %>

<%= link_to 'Show', @test_url %> |
<%= link_to 'Back', test_urls_path %>

app/views/test_urls/index.html.erb
<div class="row center bottom-margin">
  <h1>Test Urls</h1>
<%= link_to 'New Test Url', new_test_url_path, class:"btn btn-primary"%>
<%= link_to 'Refresh Schedule', restart_path, :method=>"post" , class:"btn btn-primary"%>
</div>
<div class="row index-headers">
  <div class="col-md-3 center">Url</div>
  <div class="col-md-1 center">Frequency</div>
  <div class="col-md-1 center">Request Type</div>
  <div class="col-md-1 center">Last Request Made</div>
  <div class="col-md-1 center">Code</div>
  <div class="col-md-2 center">Body</div>
  <div class="center">Actions</div>
</div>
<% @test_urls.each do |test_url| %>
  <div class="row">
    <div class="col-md-3 center overflow"><%= sweeper_or_url(test_url) %></div>
    <div class="col-md-1 center overflow"><%= test_url.frequency %></div>
    <div class="col-md-1 center overflow"><%= test_url.request %></div>
    <div class="col-md-1 center"><%= humanize_last_request_for(test_url, Time.now) %></div>
    <div class="col-md-1 center overflow"><%= test_url.response_code %></div>
    <div class="col-md-2 center overflow"><%= test_url.response_body %></div>
    <div class=" center">
      <%= link_to 'Show', test_url, class:"btn btn-primary" %>
      <%= link_to 'Edit', edit_test_url_path(test_url), class:"btn btn-warning"%>
      <%= link_to 'Destroy', test_url, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    </div>
  </div>
<% end %>
<br>

app/views/test_urls/new.html.erb
<div class="row center">
	<h1>New Test Url</h1>
</div>
<%= render 'form', test_url: @test_url %>
<%= link_to 'Back', test_urls_path %>

app/views/test_urls/show.html.erb
<div class="row center padding-top-spacer">
	<div class="row index-headers">
	  <div class="col-md-3 center">Url</div>
	  <div class="col-md-1 center">Frequency</div>
	  <div class="col-md-1 center">Request</div>
	  <div class="col-md-2 center overflow">Post Params</div>
	  <div class="col-md-1 center">Code</div>
	  <div class="col-md-2 center">Body</div>
	</div>
  <div class="row">
    <div class="col-md-3 center overflow"><%= @test_url.url %></div>
    <div class="col-md-1 center overflow"><%= @test_url.frequency %></div>
    <div class="col-md-1 center overflow"><%= @test_url.request %></div>
    <div class="col-md-2 center overflow"><%= @test_url.post_params %></div>
    <div class="col-md-1 center overflow"><%= @test_url.response_code %></div>
    <div class="col-md-2 center overflow"><%= @test_url.response_body %></div>
  </div>
	<div class="padding-top-spacer">
		<%= link_to 'Back', test_urls_path, class:"btn btn-primary" %>
		<%= link_to 'Edit', edit_test_url_path(@test_url), class:"btn btn-warning"%>
		<%= link_to 'Destroy', @test_url, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
	</div>
</div>